### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by jliby** [tfaieta/cafe#9]

**Comment by tfaieta** [comment]
Hey @Jliby let me know more about this issue so I can help you tackle it!

**Comment by JLiby** [comment]
What do you need to be contributed to the file right now?

**Comment by tfaieta** [comment]
Which file?

**Comment by tfaieta** [comment]
[This one works](https://github.com/tfaieta/Cortado/issues/5)

It's the ability to set themes for the reader, loading in different preset stylesheets like a dark/light/sepia mode. Let me know if this sounds good so I can expand on it and we can think of possible implmentations! 😄
